server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jiffymeals
    username: postgres
    password: kxke22@me
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
resilience4j:
  circuitbreaker:
    instances:
      payment_service:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 6
        ringBufferSizeInHalfOpenState: 4
        waitDurationInOpenState: 20s
        failureRateThreshold: 30
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
          - io.netty.handler.timeout.ReadTimeoutException
          - org.springframework.web.reactive.function.client.WebClientRequestException
#        failure-rate-threshold: 50
#        minimum-number-of-calls: 5
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state: 5s
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-size: 5
#        sliding-window-type: count_based
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always