server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jiffymeals
    username: postgres
    password: kxke22@me
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
jiffy:
  meals:
    gl:
      account:
        number: 8120901994
        name : Jiffy Meals
payment:
  gateway:
    base:
      url: http://localhost:8086
resilience4j.circuitbreaker:
  instances:
    account_service:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 60s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - io.netty.handler.timeout.ReadTimeoutException
        - org.springframework.web.reactive.function.client.WebClientRequestException
resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 4
      coreThreadPoolSize: 2
      queueCapacity: 2
  instances:
    account_service:
      baseConfig: default
resilience4j.retry:
  instances:
    account_service:
      maxRetryAttempts: 5
      waitDuration: 10000
      retry-exceptions:
        - java.util.concurrent.TimeoutException
#    backendB:
#      maxThreadPoolSize: 1
#      coreThreadPoolSize: 1
#      queueCapacity: 1
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always