pipeline {
    agent any
    tools {
        maven 'maven' // Ensure 'maven' matches the Maven installation name in Jenkins
    }
    environment {
        DEPLOYMENT_ENVIRONMENT = 'NO_DEPLOYMENT'
        DOCKERHUB_LOGINSERVER = ''
        APP_ENV = 'default'
        GLOBAL_ENVIRONMENT = ''
    }
    stages {
        stage('Determine Environment') {
            steps {
                echo 'Determine Environment'
                script {
                    // Determine whether this is a develop, staging, or main build
                    switch (env.GIT_BRANCH) {
                        case ~/.*develop.*/:
                            GLOBAL_ENVIRONMENT = 'develop'
                            break
                        case ~/.*staging.*/:
                            GLOBAL_ENVIRONMENT = 'staging'
                            break
                        case ~/.*main.*/:
                            GLOBAL_ENVIRONMENT = 'main'
                            break
                        default:
                            GLOBAL_ENVIRONMENT = 'NO_DEPLOYMENT'
                            break
                    }
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Building.. ' + GLOBAL_ENVIRONMENT
                script {
                    if (GLOBAL_ENVIRONMENT == 'NO_DEPLOYMENT') {
                        currentBuild.result = 'ABORTED'
                        error('This is not develop, staging, or main branch and should not be built')
                    } else {
                        echo "Hello, ${GLOBAL_ENVIRONMENT}."
                        switch (GLOBAL_ENVIRONMENT) {
                            case 'develop':
                                sh 'cd payment-service && mvn clean package -DskipTests'
                                break
                            case 'staging':
                                sh 'cd payment-service && mvn clean package'
                                sh 'ls -l payment-service/target'
                                break
                            case 'main':
                                sh 'cd payment-service && mvn clean package'
                                sh 'ls -l payment-service/target'
                                break
                            default:
                                echo 'No environment, nothing to build'
                                break
                        }
                    }
                }
            }
        }
        stage('Code Analysis') {
            steps {
                script {
                    withSonarQubeEnv('sonarsql') {
                        echo "Running SonarQube analysis"
                        dir('payment-service') {
                            sh 'mvn sonar:sonar' // Ensure SonarQube analysis is properly configured
                        }
                    }
                }
            }
        }
        stage('Publish image') {
            steps {
                script {
                    if (GLOBAL_ENVIRONMENT == 'NO_DEPLOYMENT') {
                        currentBuild.result = 'ABORTED'
                        error('This is not develop, staging, or main image and should not be published')
                    } else {
                        echo "Hello, ${GLOBAL_ENVIRONMENT}."
                        switch (GLOBAL_ENVIRONMENT) {
                            case 'develop':
                                echo "Building Docker image"
                                sh 'cd payment-service && docker build -t ujusophy/payment-service .'
                                sh "docker login -u ujusophy -p ${dockerhubpwd}"
                                sh "docker push ujusophy/payment-service"
                                echo "Image Published successfully"
                            case 'staging':
                                echo "Building Docker image"
                                sh 'cd payment-service && docker build -t ujusophy/payment-service .'
                                sh "docker login -u ujusophy -p ${dockerhubpwd}"
                                sh "docker push ujusophy/payment-service"
                                echo "Image Published successfully"
                                break
                            case 'main':
                                echo 'AWS ECR'
                                // Will be published to AWS ECR.
                                break
                            default:
                                echo 'No image to publish'
                                break
                        }
                    }
                }
            }
        }
    }
}
